// Auto-generated by scripts/generate-image-manifest.mjs
// Do not edit manually.

export type ImageManifest = {
  carousel: string[];
  finishes: string[];
  works: string[];
  projects: Array<{ name: string; images: string[] }>;
};

export const imageManifest: ImageManifest = {
  "carousel": [
    "/carousel/1.jpg",
    "/carousel/2.jpg",
    "/carousel/3.jpg",
    "/carousel/4.jpg",
    "/carousel/5.jpg",
    "/carousel/6.jpg",
    "/carousel/7.jpg",
    "/carousel/8.jpg"
  ],
  "finishes": [
    "/finishes/0da637d6-3755-40ac-a62b-6b470abbcbe8.jpg",
    "/finishes/1df94ead-efac-4fae-8609-8bda6b0fb874.jpg",
    "/finishes/5e4581e7-1221-419d-a737-295367790c75.jpg",
    "/finishes/8b148f2d-bbee-4087-a393-7c62dd6d0408.jpg",
    "/finishes/9aacc4e2-537c-424a-835e-b72807a90abd.jpg",
    "/finishes/24df2d9f-0751-4346-99df-3102d131e261.jpg",
    "/finishes/32acf400-b99f-447a-8171-13de890b0c11.jpg",
    "/finishes/76d5419f-a154-42e1-be6b-a1bd77d62aaa.jpg",
    "/finishes/93e5057f-5a7c-432e-a8b7-91a32e4f7407.jpg",
    "/finishes/191ea5e9-91d4-46cb-b16c-b7c439d8e0cb.jpg",
    "/finishes/213c40d2-66f4-43e7-a3d0-a9837da46645.jpg",
    "/finishes/589a526d-a719-4c04-815a-bef26a32c1c5.jpg",
    "/finishes/865ace3c-274f-40a0-8a08-966f57b15bb9.jpg",
    "/finishes/9282a0d6-acda-4e39-a762-d8d14ab334db.jpg",
    "/finishes/b1bbeb8c-a69e-44db-a376-593d287e7ad2.jpg",
    "/finishes/ba0a7141-ddb7-48e4-861b-14169a20deb2.jpg",
    "/finishes/e48f066e-db65-4928-aab0-d5e93d9842d5.jpg",
    "/finishes/e77f21de-267a-44d7-b2ac-25ada0e147a6.jpg",
    "/finishes/fb6da198-4819-47f3-9a9c-816c700a8554.jpg"
  ],
  "works": [
    "/works/0b602c43-791b-46c3-877a-1636c195066b.jpg",
    "/works/4f35f014-709c-4dff-bab6-1763454b01e6.jpg",
    "/works/004fe932-010d-441e-9e6c-ff202c3f854f.jpg",
    "/works/00426b24-589c-4318-bb98-ad9b1be8757b.jpg",
    "/works/46110758-9f4d-4138-a5cb-89e2010dbe96.jpg",
    "/works/e60d25dd-a38d-4e0e-8bd8-e44ceb7df66a.jpg",
    "/works/fc40b775-93ff-4226-aff1-74bbe21ef3ec.jpg"
  ],
  "projects": [
    {
      "name": "Ealing, London W5",
      "images": [
        "/projects/Ealing, London W5/1.jpg",
        "/projects/Ealing, London W5/2.jpg",
        "/projects/Ealing, London W5/3.jpg",
        "/projects/Ealing, London W5/4.jpg",
        "/projects/Ealing, London W5/5.jpg",
        "/projects/Ealing, London W5/6.jpg",
        "/projects/Ealing, London W5/7.jpg",
        "/projects/Ealing, London W5/8.jpg",
        "/projects/Ealing, London W5/9.jpg",
        "/projects/Ealing, London W5/10.jpg"
      ]
    },
    {
      "name": "Ealing, London W5 2",
      "images": [
        "/projects/Ealing, London W5 2/1.jpg",
        "/projects/Ealing, London W5 2/2.jpg",
        "/projects/Ealing, London W5 2/3.jpg",
        "/projects/Ealing, London W5 2/4.jpg",
        "/projects/Ealing, London W5 2/5.jpg",
        "/projects/Ealing, London W5 2/6.jpg",
        "/projects/Ealing, London W5 2/7.jpg",
        "/projects/Ealing, London W5 2/8.jpg",
        "/projects/Ealing, London W5 2/9.jpg",
        "/projects/Ealing, London W5 2/10.jpg"
      ]
    },
    {
      "name": "Hammersmith and Fulham",
      "images": [
        "/projects/Hammersmith and Fulham/1.jpg",
        "/projects/Hammersmith and Fulham/2.jpg",
        "/projects/Hammersmith and Fulham/3.jpg",
        "/projects/Hammersmith and Fulham/4.jpg",
        "/projects/Hammersmith and Fulham/5.jpg",
        "/projects/Hammersmith and Fulham/6.jpg",
        "/projects/Hammersmith and Fulham/7.jpg",
        "/projects/Hammersmith and Fulham/8.jpg",
        "/projects/Hammersmith and Fulham/9.jpg",
        "/projects/Hammersmith and Fulham/10.jpg"
      ]
    },
    {
      "name": "Maida Vale, London",
      "images": [
        "/projects/Maida Vale, London/1.jpg",
        "/projects/Maida Vale, London/2.jpg",
        "/projects/Maida Vale, London/3.jpg",
        "/projects/Maida Vale, London/4.jpg",
        "/projects/Maida Vale, London/5.jpg",
        "/projects/Maida Vale, London/6.jpg",
        "/projects/Maida Vale, London/7.jpg",
        "/projects/Maida Vale, London/8.jpg",
        "/projects/Maida Vale, London/9.jpg"
      ]
    },
    {
      "name": "Stanmore",
      "images": [
        "/projects/Stanmore/1.jpg",
        "/projects/Stanmore/2.jpg",
        "/projects/Stanmore/3.jpg",
        "/projects/Stanmore/4.jpg",
        "/projects/Stanmore/5.jpg",
        "/projects/Stanmore/6.jpg",
        "/projects/Stanmore/7.jpg",
        "/projects/Stanmore/8.jpg",
        "/projects/Stanmore/9.jpg",
        "/projects/Stanmore/10.jpg"
      ]
    }
  ]
};
